src/MarketWeb.Web.Mvc/Controllers/MyOrdersController.cs
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using MarketWeb.Controllers;
using MarketWeb.Orders;
using MarketWeb.Orders.Dtos;
using MarketWeb.Products;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketWeb.Web.Controllers
{
    [AbpMvcAuthorize]
    public class MyOrdersController : MarketWebControllerBase
    {
        private readonly IOrderAppService _orderAppService;
        private readonly IProductAppService _productAppService;
        public MyOrdersController(IOrderAppService orderAppService, IProductAppService productAppService)
        {
            _orderAppService = orderAppService;
            _productAppService = productAppService;
        }

        public async Task<IActionResult> Index()
        {
            var orders = await _orderAppService.GetUserOrders();
            foreach (var item in orders.Items)
                await SetOrderItemProducts(item.Items);

            return View(orders.Items);
        }

        public async Task<IActionResult> Details(long orderId)
        {
            var userOrders = await _orderAppService.GetUserOrders();
            var targetOrder = userOrders.Items.FirstOrDefault(o => o.Id == orderId);
            if (targetOrder is null)
                return NotFound();
            await SetOrderItemProducts(targetOrder.Items);
            return View(targetOrder);
        }

        private async Task SetOrderItemProducts(ICollection<OrderItemDto> orderItems)
        {
            foreach (var orderItem in orderItems)
                orderItem.Product = await _productAppService.GetAsync(new EntityDto<long> { Id = orderItem.ProductID });
        }
    }
}

src/MarketWeb.Web.Mvc/Controllers/ProductsController.cs
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using MarketWeb.Authorization;
using MarketWeb.Carts;
using MarketWeb.Controllers;
using MarketWeb.Products;
using MarketWeb.Products.Dtos;
using MarketWeb.Web.Models.Products;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace MarketWeb.Web.Controllers
{
    public class ProductsController : MarketWebControllerBase
    {
        private readonly IProductAppService _productAppService;
        private readonly ICartAppService _cartAppService;
        public ProductsController(IProductAppService productAppService, ICartAppService cartAppService)
        {
            _productAppService = productAppService;
            _cartAppService = cartAppService;
        }

        public async Task<IActionResult> Index(string keyword)
        {
            var products = await _productAppService.GetAllAsync(new PagedProductResultRequestDto { Keyword = keyword });
            var model = new ProductViewModel() { Products = products };
            if (User.Identity.IsAuthenticated)
                model.ProductsInUserCart = await _cartAppService.GetUserCartProductsAsync();
            return View(model);
        }

        public async Task<IActionResult> Details(long id)
        {
            var product = await _productAppService.GetAsync(new EntityDto<long>(id));
            if (product == null)
                return NotFound();
            if (User.Identity.IsAuthenticated)
                ViewBag.IsInCart = (await _cartAppService.GetUserCartProductsAsync()).Select(p => p.Id).Contains(id);
            return View(product);
        }

        [AbpMvcAuthorize(PermissionNames.ProductsARU)]
        public async Task<IActionResult> Delete(long id)
        {
            await _productAppService.DeleteAsync(new EntityDto<long>(id));
            return RedirectToAction(nameof(Index));
        }

        [AbpMvcAuthorize(PermissionNames.ProductsARU)]
        public async Task<IActionResult> Edit(long id)
        {
            var product = await _productAppService.GetAsync(new EntityDto<long>(id));
            if (product is null)
                return NotFound();
            return View(product);
        }
        [AbpMvcAuthorize(PermissionNames.ProductsARU)]
        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Name,Price")] ProductDto product, long id, long companyID)
        {
            if (ModelState.IsValid)
            {
                product.Id = id;
                product.CompanyID = companyID;
                product = await _productAppService.UpdateAsync(product);
                return RedirectToAction(nameof(Details), new { id = product.Id });
            }
            return View();
        }
    }
}

src/MarketWeb.Web.Mvc/Views/MyOrders/Details.cshtml
@using MarketWeb.Web.Startup
@using MarketWeb.Orders.Dtos

@model OrderDto

@{
    ViewBag.Title = L("MyOrders");
    ViewBag.CurrentPageName = PageNames.MyOrders;
}

<h2>
    Order Created At @Html.DisplayFor(model => model.CreationTime)
</h2>
<br />

<h3>
    Order State : @MarketWeb.Orders.OrderState.State2String[Model.State]
</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Product.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Product.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.FirstOrDefault().Count)
            </th>
            <th>
                @L("TotalPrice")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    <a asp-controller="Products" asp-action="Details" asp-route-id="@item.ProductID">
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Count)
                </td>
                <td>
                    @item.TotalPrice()
                </td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>
                @Model.TotalOrderPrice()
            </td>
        </tr>
    </tbody>
</table>

<a asp-action="Index">Back To Orders</a>

src/MarketWeb.Web.Mvc/Views/MyOrders/Index.cshtml
@using MarketWeb.Web.Startup
@using MarketWeb.Orders.Dtos
@using MarketWeb.Orders

@model IEnumerable<OrderDto>

@{
    ViewBag.Title = L("MyOrders");
    ViewBag.CurrentPageName = PageNames.MyOrders;
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CreationTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                Total Price
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationTime)
                </td>
                <td>
                    @OrderState.State2String[item.State]
                </td>
                <td>
                    @item.TotalOrderPrice()
                </td>
                <td>
                    <a asp-controller="MyOrders" asp-action="Details" asp-route-orderId="@item.Id">@L("Details")</a>
                </td>
            </tr>
        }
    </tbody>
</table>